// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mpjktpgsiwgkrdnnqrkz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1wamt0cGdzaXdna3Jkbm5xcmt6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1NDg0NjksImV4cCI6MjA3MTEyNDQ2OX0.0byT7zwk1cnqes67m84hr1-pn22j16TTMgoKD-7URK0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});